### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lsolniczek** [steelbrain/autocomplete-swift#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [autocomplete-swift](https://github.com/steelbrain/autocomplete-swift) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/lukasz/.atom/packages/autocomplete-swift/lib/index.js:17

TypeError: Cannot read property 'length' of undefined
    at /Users/lukasz/.atom/packages/autocomplete-swift/lib/index.js:17:34
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
  4x -1:59.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-elixir, v1.5.12
autocomplete-erlang, v1.1.1
autocomplete-swift, v1.0.0
build-elixir, v0.6.0
language-elixir, v0.5.2
language-erlang, v3.0.0
language-swift, v0.4.0
linter-swiftc, v2.0.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
The error could be handled gracefully
