### ISSUE TITLE
Failed to load the autocomplete-swift package

### ISSUE THREAD

**Issue by Diego5529** [steelbrain/autocomplete-swift#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [autocomplete-swift](https://github.com/steelbrain/autocomplete-swift) package 1.0.3

### Stack Trace

Failed to load the autocomplete-swift package

```
At Cannot find module './api'

Error: Cannot find module './api'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/autocomplete-swift/lib/index.js:7:12)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -4:30.1.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.8.0 core:confirm (input.hidden-input)
     -3:43.6.0 core:select-all (input.hidden-input)
     -3:38.8.0 core:confirm (input.hidden-input)
     -3:28 core:select-all (input.hidden-input)
     -3:17.5.0 core:confirm (input.hidden-input)
     -3:08.5.0 core:select-all (input.hidden-input)
     -3:04.2.0 core:confirm (input.hidden-input)
     -2:57 core:select-all (input.hidden-input)
     -2:54.3.0 core:backspace (input.hidden-input)
     -2:51.1.0 core:confirm (input.hidden-input)
     -2:32.6.0 core:backspace (input.hidden-input)
     -2:01.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  5x -1:56.8.0 core:backspace (input.hidden-input)
     -1:52.1.0 core:save (input.hidden-input)
  4x -1:33.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-xcode 0.1.3 
autocomplete-swift 1.0.3 
language-swift 0.5.0 
swift-debugger 0.1.2 
```

**Comment by steelbrain** [comment]
The solution for this

is to turn it off and on again 😄 
If restarting Atom doesn't fix, try `apm uninstall autocomplete-swift` then `apm install autocomplete-swift`
